# Welcome to the Jekyll config file for Scalar product documentation!
#
# This config file is meant for settings that affect the entire site for this set of Scalar parent product docs. 
# After initially setting up this parent product docs site, the values in this config file should rarely be edited. 
# If edits are needed to this config file, you may need to consider editing the config files of other Scalar parent product docs sites so that we can ensure consistency.
# For technical reasons, this file is *NOT* reloaded automatically when you use `jekyll serve`. 
# If you change this file, please restart the server process.

# When adding versioned docs, add a new config file in the root folder of the repository, with a base URL containing the product and version in the following format: `_config.<PARENT_PRODUCT_NAME>.<X.X.X>`

remote_theme             : "mmistakes/minimal-mistakes@4.24.0"

minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "ScalarDB documentation &#124; Scalar, Inc." # To change the "| Docs" site title, see `includes/masthead.html`.
title_separator          : "-"
#subtitle                 : ""
description              : &description "Cloud-native universal transaction manager in microservice era" # the official description of the parent product
url                      : "localhost" # the base hostname & protocol for your site (i.e., "https://docs.scalar-labs.com"); use `localhost` for testing locally
baseurl                  : "/scalardb" # The subpath of the parent product docs site (e.g. "/scalardb"). When selecting the "Scalar Docs" logo, you will be taken to the Scalar Docs site (`https://docs.scalar-labs.com/`). For the URL, see `includes/masthead.html`.
repository               : "scalar-labs/docs-scalardb" # the repository path of the Scalar parent product (e.g., scalar-labs/docs-scalardb)
logo                     : "/assets/images/scalar-logo.png" # the Scalar company logo
breadcrumbs              : # true or false (default)

#atom_feed:
#  path                   : # blank (default) uses feed.xml

# Search function
search                   : true # true, false (default)
search_full_content      : true # true, false (default)
search_provider          : lunr
lunr:
  search_within_pages: true

# SEO Related
google_site_verification : # Replace this with your ID, or delete; not necessary since we have included our Google Analytics tracking ID
bing_site_verification   : # Replace this with your ID, or delete

# Social Sharing
twitter:
  username               : &twitter "scalar_labs"
og_image                 : "/assets/images/scalar-logo.png" # Open Graph/Twitter default site image
# For specifying social profiles, used in _includes/seo.html
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : Organization # Person or Organization (defaults to Person)
  name                   : Scalar Inc. # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles that appear in the Google Knowledge Panel in search results
    - "https://twitter.com/scalar_labs"
    - "https://github.com/scalar-labs"
    - "https://www.linkedin.com/company/scalarlabs"
    - "https://www.facebook.com/scalar.labs"

# Analytics
analytics:
  provider               : "google-gtag" # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : G-Q4TKS77KCP # Replace this with your ID, or delete
    anonymize_ip         : false

# Site Footer
footer:
  links:
    - label: "" # Leave `label` blank so that only the social icon appears
      icon: "fab fa-fw fa-github"
      url: "https://github.com/scalar_labs"
    - label: "" # Leave `label` blank so that only the social icon appears
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/scalar.labs"
    - label: "" # Leave `label` blank so that only the social icon appears
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/scalar_labs"
    - label: "" # Leave `label` blank so that only the social icon appears
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/company/scalarlabs"

# Reading Files
include:
  - .htaccess
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

## Mermaid support
mermaid: true

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  home:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # Parent product home page defaults
  - scope:
      path: "_home" # the name of the folder where the parent product docs home page is located
      type: home # for the parent product home page, `home` is the default
    values:
      layout: page # the type of template used from the "_layouts" folder
      read_time: false # show the average reading time for the page
      share: false # show social media buttons to share the page
      sidebar: # navigation content
        nav: "side-nav"
      toc: false
      toc_sticky: false
      classes: wide # Expands page to take up space where the TOC would normally be
  # Documentation page defaults
  - scope:
      path: "" # the name of the folder where the docs home page is located
      type: pages # for docs pages, `pages` is the default
    values:
      layout: page # the type of template used from the "_layouts" folder
      read_time: false # show the average reading time for the page
      share: false # show social media buttons to share the page
      sidebar: # navigation content
        nav: "side-nav"
      toc: true
      toc_sticky: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
# permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
# timezone: Asia/Tokyo # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
# category_archive:
#  type: liquid
#  path: /categories/
# tag_archive:
#  type: liquid
#  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
