/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  /* tutorialSidebar: [{type: 'autogenerated', dirName: '.'}], */

  // But you can create a sidebar manually

  // English sidebar nav
  docsEnglish: [
    {
      type: 'doc',
      label: 'ScalarDB Docs Home',
      id: 'index',
    },
    {
      type: 'category',
      label: 'About ScalarDB',
      collapsible: true,
      items: [
        {
          type: 'doc',
          id: 'overview',
          label: 'Overview',
        },
        {
          type: 'doc',
          id: 'design',
          label: 'Design',
        },
        {
          type: 'doc',
          id: 'requirements',
          label: 'Requirements',
        },
        {
          type: 'doc',
          id: 'database-configurations',
          label: 'Underlying Database Configurations',
        },
        {
          type: 'doc',
          id: 'releases/release-notes',
          label: 'Release Notes',
        },
        {
          type: 'doc',
          id: 'releases/release-support-policy',
          label: 'Release Support Policy',
        },
        {
          type: 'doc',
          id: 'roadmap',
          label: 'Roadmap',
        },
      ],
    },
    {
      type: 'category',
      label: 'Quickstart',
      collapsible: true,
      items: [
        {
          type: 'doc',
          id: 'quick-start-overview',
          label: 'Overview',
        },
        {
          type: 'category',
          label: 'Try Running Transactions Through the ScalarDB Core Library',
          collapsible: true,
          items: [
            {
              type: 'doc',
              id: 'getting-started-with-scalardb',
              label: 'Use ScalarDB Core',
            },
            {
              type: 'doc',
              id: 'getting-started-with-scalardb-by-using-kotlin',
              label: 'Use Kotlin',
            },
          ],
        },
        {
          type: 'category',
          label: 'Try Running Transactions Through ScalarDB Cluster',
          collapsible: true,
          items: [
            {
              type: 'doc',
              id: 'scalardb-cluster/getting-started-with-scalardb-cluster',
              label: 'Use ScalarDB Cluster',
            },
            {
              type: 'doc',
              id: 'scalardb-cluster/getting-started-with-scalardb-cluster-sql-jdbc',
              label: 'Use SQL via JDBC',
            },
            {
              type: 'doc',
              id: 'scalardb-cluster/getting-started-with-scalardb-cluster-sql-spring-data-jdbc',
              label: 'Use SQL via Spring Data JDBC',
            },
            {
              type: 'doc',
              id: 'scalardb-cluster/getting-started-with-scalardb-cluster-graphql',
              label: 'Use GraphQL',
            },
          ],
        },
        {
          type: 'category',
          label: 'Try Running Analytical Queries Through ScalarDB Analytics',
          collapsible: true,
          items: [
            {
              type: 'doc',
              id: 'scalardb-analytics-postgresql/getting-started',
              label: 'Use ScalarDB Analytics with PostgreSQL',
            },
            {
              type: 'doc',
              id: 'scalardb-samples/scalardb-analytics-spark-sample/README',
              label: 'Use ScalarDB Analytics',
            },
          ],
        },
        {
          type: 'category',
          label: 'Reference',
          collapsible: true,
          items: [
            {
              type: 'doc',
              id: 'scalardb-cluster/getting-started-with-using-go-for-scalardb-cluster',
              label: 'Use Go for ScalarDB Cluster',
            },
            {
              type: 'doc',
              id: 'scalardb-cluster/getting-started-with-using-python-for-scalardb-cluster',
              label: 'Use Python for ScalarDB Cluster',
            },
            {
              type: 'doc',
              id: 'scalardb-analytics-postgresql/installation',
              label: 'Install ScalarDB Analytics with PostgreSQL Locally',
            }
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Develop',
      collapsible: true,
      items: [
        {
          type: 'doc',
          id: 'develop-overview',
          label: 'Overview',
        },
        {
          type: 'category',
          label: 'Run Transactions',
          collapsible: true,
          items: [
            {
              type: 'doc',
              id: 'data-modeling',
              label: 'Model Your Data',
            },
            {
              type: 'category',
              label: 'Run Through the CRUD Interface',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'run-transactions-through-scalardb-core-library',
                  label: 'Use the ScalarDB Core Library',
                },
                {
                  type: 'doc',
                  id: 'scalardb-cluster/run-transactions-through-scalardb-cluster',
                  label: 'Use ScalarDB Cluster',
                },
              ],
            },
            {
              type: 'doc',
              id: 'scalardb-cluster/run-transactions-through-scalardb-cluster-sql',
              label: 'Run Through the SQL Interface',
            },
            {
              type: 'category',
              label: 'Advanced Configurations and Operations',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'scalardb-cluster/scalardb-auth-with-sql',
                  label: 'Authenticate and Authorize Users by Using SQL',
                },
                {
                  type: 'doc',
                  id: 'scalardb-benchmarks/README',
                  label: 'Run Benchmarks',
                },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Run Analytical Queries',
          collapsible: true,
          items: [
            {
              type: 'doc',
              id: 'scalardb-samples/scalardb-analytics-postgresql-sample/README',
              label: 'Run ScalarDB Analytics with PostgreSQL',
            },
            // This doc no longer exists but we should have some type of doc here.
            // {
            //   type: 'doc',
            //   id: 'scalardb-analytics-spark/getting-started',
            //   label: 'Run ScalarDB Analytics',
            // },
          ],
        },
        {
          type: 'category',
          label: 'Run Non-Transactional Storage Operations',
          collapsible: true,
          items: [
            {
              type: 'category',
              label: 'Run Through the CRUD Interface',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'run-non-transactional-storage-operations-through-library',
                  label: 'Use the ScalarDB Core Library',
                },
                {
                  type: 'doc',
                  id: 'scalardb-cluster/run-non-transactional-storage-operations-through-scalardb-cluster',
                  label: 'Use ScalarDB Cluster',
                },
              ],
            },
            {
              type: 'doc',
              id: 'scalardb-cluster/run-non-transactional-storage-operations-through-sql-interface',
              label: 'Run Through the SQL Interface',
            },
            {
              type: 'doc',
              id: 'run-non-transactional-storage-operations-through-primitive-crud-interface',
              label: 'Run Through the Primitive CRUD Interface',
            },
          ],
        },
        {
          type: 'category',
          label: 'Run Sample Applications',
          collapsible: true,
          items: [
            {
              type: 'doc',
              id: 'scalardb-samples/multi-storage-transaction-sample/README',
              label: 'Multi-Storage Transactions',
            },
            {
              type: 'doc',
              id: 'scalardb-samples/microservice-transaction-sample/README',
              label: 'Microservice Transactions',
            },
            {
              type: 'doc',
              id: 'scalardb-samples/spring-data-multi-storage-transaction-sample/README',
              label: 'Multi-Storage Transactions Through Spring Data JDBC',
            },
            {
              type: 'doc',
              id: 'scalardb-samples/spring-data-microservice-transaction-sample/README',
              label: 'Microservice Transactions Through Spring Data JDBC',
            },
          ],
        },
        {
          type: 'category',
          label: 'Reference',
          collapsible: true,
          items: [
            {
              type: 'doc',
              id: 'add-scalardb-to-your-build',
              label: 'Add ScalarDB to Your Build',
            },
            {
              type: 'doc',
              id: 'configurations',
              label: 'ScalarDB Configurations',
            },
            {
              type: 'doc',
              id: 'api-guide',
              label: 'API Guide',
            },
            {
              type: 'doc',
              id: 'two-phase-commit-transactions',
              label: 'Two-Phase Commit Transactions',
            },
            {
              type: 'doc',
              id: 'multi-storage-transactions',
              label: 'Multi-Storage Transactions',
            },
            {
              type: 'doc',
              id: 'schema-loader',
              label: 'Schema Loader',
            },
            {
              type: 'doc',
              id: 'scalardb-cluster/compatibility',
              label: 'ScalarDB Cluster Compatibility Matrix',
            },
            {
              type: 'doc',
              id: 'scalardb-cluster/developer-guide-for-scalardb-cluster-with-java-api',
              label: 'ScalarDB Cluster Java API',
            },
            {
              type: 'doc',
              id: 'scalardb-cluster/scalardb-cluster-configurations',
              label: 'ScalarDB Cluster Configurations',
            },
            {
              type: 'doc',
              id: 'scalardb-cluster/scalardb-cluster-grpc-api-guide',
              label: 'ScalarDB Cluster gRPC API Guide',
            },
            {
              type: 'doc',
              id: 'scalardb-cluster/encrypt-data-at-rest',
              label: 'Encrypt Data at Rest',
            },
            {
              type: 'doc',
              id: 'scalardb-cluster/encrypt-wire-communications',
              label: 'Encrypt Wire Communications',
            },
            {
              type: 'category',
              label: 'SQL Interface',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'scalardb-sql/jdbc-guide',
                  label: 'JDBC Guide',
                },
                {
                  type: 'doc',
                  id: 'scalardb-sql/sql-api-guide',
                  label: 'API Guide',
                },			
                {
                  type: 'doc',
                  id: 'scalardb-cluster/scalardb-cluster-sql-grpc-api-guide',
                  label: 'gRPC API Guide',
                },
                {
                  type: 'doc',
                  id: 'scalardb-sql/spring-data-guide',
                  label: 'Spring Data Guide',
                },
                {
                  type: 'doc',
                  id: 'scalardb-sql/grammar',
                  label: 'Grammar',
                },
              ],
            },
            {
              type: 'category',
              label: 'GraphQL Interface',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'scalardb-graphql/how-to-run-two-phase-commit-transaction',
                  label: 'Two-Phase Commit Transactions',
                },
              ],
            },
            {
              type: 'category',
              label: 'Analytics',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'scalardb-analytics-postgresql/scalardb-fdw',
                  label: 'ScalarDB FDW for PostgreSQL',
                },
                {
                  type: 'doc',
                  id: 'scalardb-analytics-postgresql/schema-importer',
                  label: 'PostgreSQL Schema Importer for PostgreSQL',
                },
                {
                  type: 'doc',
                  id: 'scalardb-analytics-spark/version-compatibility',
                  label: 'Version Compatibility for Spark',
                },
              ],
            },
            {
              type: 'category',
              label: '.NET',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'scalardb-cluster-dotnet-client-sdk/index',
                  label: 'Overview',
                },
                {
                  type: 'doc',
                  id: 'scalardb-cluster-dotnet-client-sdk/getting-started-with-distributed-transactions',
                  label: 'Distributed Transactions',
                },
                {
                  type: 'doc',
                  id: 'scalardb-cluster-dotnet-client-sdk/getting-started-with-distributed-sql-transactions',
                  label: 'Distributed SQL Transactions',
                },
                {
                  type: 'doc',
                  id: 'scalardb-cluster-dotnet-client-sdk/getting-started-with-admin-api',
                  label: 'Administrative API',
                },
                {
                  type: 'doc',
                  id: 'scalardb-cluster-dotnet-client-sdk/getting-started-with-scalardb-tables-as-csharp-classes',
                  label: 'Tables as C# Classes',
                },
                {
                  type: 'doc',
                  id: 'scalardb-cluster-dotnet-client-sdk/getting-started-with-aspnet-and-di',
                  label: 'ASP.NET Core and Dependency Injection',
                },
                {
                  type: 'doc',
                  id: 'scalardb-cluster-dotnet-client-sdk/getting-started-with-linq',
                  label: 'LINQ',
                },
                {
                  type: 'doc',
                  id: 'scalardb-cluster-dotnet-client-sdk/getting-started-with-two-phase-commit-transactions',
                  label: 'Two-Phase Commit Transactions',
                },
                {
                  type: 'doc',
                  id: 'scalardb-cluster-dotnet-client-sdk/getting-started-with-auth',
                  label: 'Authenticate and Authorize Users',
                },
                {
                  type: 'doc',
                  id: 'scalardb-cluster-dotnet-client-sdk/exception-handling',
                  label: 'Handle Exceptions',
                },
                {
                  type: 'doc',
                  id: 'scalardb-cluster-dotnet-client-sdk/common-reference',
                  label: 'Common Reference',
                },
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Deploy',
      collapsible: true,
      items: [
        {
          type: 'doc',
          id: 'deploy-overview',
          label: 'Overview',
        },
        {
          type: 'doc',
          id: 'scalardb-cluster/setup-scalardb-cluster-on-kubernetes-by-using-helm-chart',
          label: 'Deploy ScalarDB Cluster Locally',
        },
        {
          type: 'doc',
          id: 'scalar-kubernetes/ManualDeploymentGuideScalarDBClusterOnEKS',
          label: 'Deploy ScalarDB Cluster on Amazon EKS',
        },
        {
          type: 'category',
          label: 'Reference',
          collapsible: true,
          items: [
            {
              type: 'doc',
              id: 'scalardb-cluster/standalone-mode',
              label: 'ScalarDB Cluster Standalone Mode',
            },
            {
              type: 'doc',
              id: 'scalar-kubernetes/ProductionChecklistForScalarDBCluster',
              label: 'Production Checklist for ScalarDB Cluster',
            },
            {
              type: 'category',
              label: 'Getting Started Guides',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'helm-charts/getting-started-scalar-helm-charts',
                  label: 'Scalar Helm Charts',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/getting-started-scalardb-cluster-tls',
                  label: 'ScalarDB Cluster with TLS by Using a Helm Chart',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/getting-started-scalardb-cluster-tls-cert-manager',
                  label: 'ScalarDB Cluster with TLS by Using cert-manager and a Helm Chart',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/getting-started-scalardb-analytics-postgresql',
                  label: 'ScalarDB Analytics with PostgreSQL by Using a Helm Chart',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/getting-started-monitoring',
                  label: 'Prometheus Operator for Monitoring by Using a Helm Chart',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/getting-started-logging',
                  label: 'Loki Stack for Logging by Using a Helm Chart',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/getting-started-scalar-manager',
                  label: 'Scalar Manager by Using a Helm Chart',
                },
              ],
            },
            {
              type: 'category',
              label: 'Database Setup Guides',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/SetupDatabaseForAWS',
                  label: 'AWS',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/SetupDatabaseForAzure',
                  label: 'Azure',
                },
              ],
            },
            {
              type: 'category',
              label: 'Installation Guides',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/HowToGetContainerImages',
                  label: 'Get Container Images',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/AwsMarketplaceGuide',
                  label: 'Install From AWS Marketplace',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/HowToUseContainerImages',
                  label: 'Use Container Images',
                },
              ],
            },
            {
              type: 'category',
              label: 'Deployment Guides',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/CreateEKSClusterForScalarDBCluster',
                  label: 'Create an EKS Cluster for ScalarDB Cluster',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/CreateBastionServer',
                  label: 'Create a Bastion Server',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/how-to-deploy-scalardb-cluster',
                  label: 'Deploy ScalarDB Cluster by Using a Helm Chart',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/how-to-deploy-scalardb-analytics-postgresql',
                  label: 'Deploy ScalarDB Analytics with PostgreSQL by Using a Helm Chart',
                },
              ],
            },
            {
              type: 'category',
              label: 'Configuration Guides',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/AccessScalarProducts',
                  label: 'Access Kubernetes environment from applications',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/HowToCreateKeyAndCertificateFiles',
                  label: 'Create Private Key and Certificate Files',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/configure-custom-values-scalardb-cluster',
                  label: 'Configure a custom values file for ScalarDB Cluster',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/configure-custom-values-scalardb-analytics-postgresql',
                  label: 'Configure a Custom Values File for ScalarDB Analytics with PostgreSQL',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/configure-custom-values-scalar-admin-for-kubernetes',
                  label: 'Configure a Custom Values File for Scalar Admin for Kubernetes',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/configure-custom-values-scalar-manager',
                  label: 'Configure a Custom Values File for Scalar Manager',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/configure-custom-values-envoy',
                  label: 'Configure a Custom Values File for Scalar Envoy',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/mount-files-or-volumes-on-scalar-pods',
                  label: 'Mount Files or Volumes on ScalarDB Pods',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/use-secret-for-credentials',
                  label: 'Use Secret Resources',
                },
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Migrate',
      collapsible: true,
      items: [
        {
          type: 'doc',
          id: 'schema-loader-import',
          label: 'Import Existing Tables',
        },
        {
          'type': 'doc',
          'id': 'scalardb-sql/migration-guide',
          'label': 'Migrate Applications and Databases',
        }
      ],
    },
    {
      type: 'category',
      label: 'Manage',
      collapsible: true,
      items: [
        {
          type: 'doc',
          id: 'scalar-kubernetes/HowToScaleScalarDB',
          label: 'Scale',
        },
        {
          type: 'doc',
          id: 'scalar-kubernetes/HowToUpgradeScalarDB',
          label: 'Upgrade',
        },
        {
          type: 'category',
          label: 'Monitor',
          collapsible: true,
          items: [
            {
              type: 'doc',
              id: 'monitor-by-using-scalar-manager',
              label: 'Use Scalar Manager',
            },
            {
              type: 'category',
              label: 'Reference',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/K8sMonitorGuide',
                  label: 'Kubernetes Monitoring Guide',
                },
                {
                  type: 'doc',
                  id: 'scalar-manager/overview',
                  label: 'Scalar Manager Overview',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/how-to-deploy-scalar-admin-for-kubernetes',
                  label: 'Deploy Scalar Admin for Kubernetes',
                },
              ]
            },
          ],
        },
        {
          type: 'category',
          label: 'Back Up and Restore',
          collapsible: true,
          items: [
            {
              type: 'doc',
              id: 'manage-backup-and-restore',
              label: 'Back Up and Restore Databases',
            },
            {
              type: 'category',
              label: 'Reference',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'backup-restore',
                  label: 'Back Up and Restore Databases Used Through ScalarDB',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/BackupNoSQL',
                  label: 'Back Up a NoSQL Database in Kubernetes',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/RestoreDatabase',
                  label: 'Restore Databases in Kubernetes',
                },
              ]
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Troubleshoot',
      collapsible: true,
      items: [
        {
          type: 'category',
          label: 'Error Codes',
          collapsible: true,
          items: [
            {
              type: 'doc',
              id: 'scalardb-core-status-codes',
              label: 'ScalarDB Core',
            },
            {
              type: 'doc',
              id: 'scalardb-cluster/scalardb-cluster-status-codes',
              label: 'ScalarDB Cluster',
            },
            {
              type: 'doc',
              id: 'scalardb-graphql/scalardb-graphql-status-codes',
              label: 'ScalarDB GraphQL',
            },
            {
              type: 'doc',
              id: 'scalardb-sql/scalardb-sql-status-codes',
              label: 'ScalarDB SQL',
            },
            {
              type: 'doc',
              id: 'scalardb-cluster/scalardb-auth-status-codes',
              label: 'Authentication and Authorization',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsible: true,
      items: [
        {
          type: 'doc',
          id: 'scalar-licensing/README',
          label: 'Configure a Product License Key',
        },
      ],
    },
  ],

  // Japanese sidebar nav
  docsJapanese: [
    {
      type: 'doc',
      label: 'ScalarDB ドキュメンテーションホーム',
      id: 'index',
    },
    {
      type: 'category',
      label: 'ScalarDB について',
      collapsible: true,
      items: [
        {
          type: 'doc',
          id: 'overview',
          label: '概要',
        },
        {
          type: 'doc',
          id: 'design',
          label: 'デザイン',
        },
        {
          type: 'doc',
          id: 'requirements',
          label: '要件',
        },
        {
          type: 'doc',
          id: 'database-configurations',
          label: '基盤となるデータベースの設定',
        },
        {
          type: 'doc',
          id: 'releases/release-notes',
          label: 'リリースノート',
        },
        {
          type: 'doc',
          id: 'releases/release-support-policy',
          label: 'リリースサポートポリシー',
        },
        {
          type: 'doc',
          id: 'roadmap',
          label: 'ロードマップ',
        },
      ],
    },
    {
      type: 'category',
      label: 'クイックスタート',
      collapsible: true,
      items: [
        {
          type: 'doc',
          id: 'quick-start-overview',
          label: '概要',
        },
        {
          type: 'category',
          label: 'ScalarDB Core ライブラリを使用してトランザクションを実行してみる',
          collapsible: true,
          items: [
            {
              type: 'doc',
              id: 'getting-started-with-scalardb',
              label: 'ScalarDB Core を使用する',
            },
            {
              type: 'doc',
              id: 'getting-started-with-scalardb-by-using-kotlin',
              label: 'Kotlin を使用する',
            },
          ],
        },
        {
          type: 'category',
          label: 'ScalarDB Cluster を使用してトランザクションを実行してみる',
          collapsible: true,
          items: [
            {
              type: 'doc',
              id: 'scalardb-cluster/getting-started-with-scalardb-cluster',
              label: 'ScalarDB Cluster を使用する',
            },
            {
              type: 'doc',
              id: 'scalardb-cluster/getting-started-with-scalardb-cluster-sql-jdbc',
              label: 'JDBC 経由で SQL を使用する',
            },
            {
              type: 'doc',
              id: 'scalardb-cluster/getting-started-with-scalardb-cluster-sql-spring-data-jdbc',
              label: 'Spring Data JDBC 経由で SQL を使用する',
            },
            {
              type: 'doc',
              id: 'scalardb-cluster/getting-started-with-scalardb-cluster-graphql',
              label: 'GraphQL を使用する',
            },
          ],
        },
        {
          type: 'category',
          label: 'ScalarDB Analytics を使用して分析クエリを実行してみる',
          collapsible: true,
          items: [
            {
              type: 'doc',
              id: 'scalardb-analytics-postgresql/getting-started',
              label: 'ScalarDB Analytics with PostgreSQL を使用する',
            },
            {
              type: 'doc',
              id: 'scalardb-samples/scalardb-analytics-spark-sample/README',
              label: 'ScalarDB Analytics を使用する',
            },
          ],
        },
        {
          type: 'category',
          label: '詳細',
          collapsible: true,
          items: [
            {
              type: 'doc',
              id: 'scalardb-cluster/getting-started-with-using-go-for-scalardb-cluster',
              label: 'ScalarDB Cluster に Go を使用する',
            },
            {
              type: 'doc',
              id: 'scalardb-cluster/getting-started-with-using-python-for-scalardb-cluster',
              label: 'ScalarDB Cluster に Python を使用する',
            },
            {
              type: 'doc',
              id: 'scalardb-analytics-postgresql/installation',
              label: 'ScalarDB Analytics with PostgreSQL をローカルにインストールする',
            }
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '開発',
      collapsible: true,
      items: [
        {
          type: 'doc',
          id: 'develop-overview',
          label: '概要',
        },
        {
          type: 'category',
          label: 'トランザクションを実行する',
          collapsible: true,
          items: [
            {
              type: 'doc',
              id: 'data-modeling',
              label: 'データをモデル化する',
            },
            {
              type: 'category',
              label: 'CRUD インターフェースを使用して実行する',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'run-transactions-through-scalardb-core-library',
                  label: 'ScalarDB Core ライブラリーを使用',
                },
                {
                  type: 'doc',
                  id: 'scalardb-cluster/run-transactions-through-scalardb-cluster',
                  label: 'ScalarDB Cluster を使用',
                },
              ],
            },
            {
              type: 'doc',
              id: 'scalardb-cluster/run-transactions-through-scalardb-cluster-sql',
              label: 'SQL インターフェースを使用して実行する',
            },
            {
              type: 'category',
              label: '高度な設定と操作',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'scalardb-cluster/scalardb-auth-with-sql',
                  label: 'SQL を使用してユーザーを認証および承認する',
                },
                {
                  type: 'doc',
                  id: 'scalardb-benchmarks/README',
                  label: 'ベンチマークを実行する',
                },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: '分析クエリを実行する',
          collapsible: true,
          items: [
            {
              type: 'doc',
              id: 'scalardb-samples/scalardb-analytics-postgresql-sample/README',
              label: 'ScalarDB Analytics with PostgreSQL を実行する',
            },
            // This doc no longer exists but we should have some type of doc here.
            // {
            //   type: 'doc',
            //   id: 'scalardb-analytics-spark/getting-started',
            //   label: 'Run ScalarDB Analytics',
            // },
          ],
        },
        {
          type: 'category',
          label: '非トランザクションストレージ操作を実行する',
          collapsible: true,
          items: [
            {
              type: 'category',
              label: 'CRUD インターフェースを使用して実行する',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'run-non-transactional-storage-operations-through-library',
                  label: 'ScalarDB Core ライブラリーを使用する',
                },
                {
                  type: 'doc',
                  id: 'scalardb-cluster/run-non-transactional-storage-operations-through-scalardb-cluster',
                  label: 'ScalarDB Cluster を使用する',
                },
              ],
            },
            {
              type: 'doc',
              id: 'scalardb-cluster/run-non-transactional-storage-operations-through-sql-interface',
              label: 'SQL インターフェースを使用して実行する',
            },
            {
              type: 'doc',
              id: 'run-non-transactional-storage-operations-through-primitive-crud-interface',
              label: 'プリミティブ CRUD インターフェースを使用して実行する',
            },
          ],
        },
        {
          type: 'category',
          label: 'サンプルアプリケーションを実行する',
          collapsible: true,
          items: [
            {
              type: 'doc',
              id: 'scalardb-samples/multi-storage-transaction-sample/README',
              label: 'マルチストレージトランザクション',
            },
            {
              type: 'doc',
              id: 'scalardb-samples/microservice-transaction-sample/README',
              label: 'マイクロサービストランザクション',
            },
            {
              type: 'doc',
              id: 'scalardb-samples/spring-data-multi-storage-transaction-sample/README',
              label: 'Spring Data JDBC によるマルチストレージトランザクション',
            },
            {
              type: 'doc',
              id: 'scalardb-samples/spring-data-microservice-transaction-sample/README',
              label: 'Spring Data JDBC によるマイクロサービストランザクション',
            },
          ],
        },
        {
          type: 'category',
          label: '詳細',
          collapsible: true,
          items: [
            {
              type: 'doc',
              id: 'add-scalardb-to-your-build',
              label: 'ビルドに ScalarDB を追加する',
            },
            {
              type: 'doc',
              id: 'configurations',
              label: 'ScalarDB の設定',
            },
            {
              type: 'doc',
              id: 'api-guide',
              label: 'API ガイド',
            },
            {
              type: 'doc',
              id: 'two-phase-commit-transactions',
              label: '2 フェーズコミットトランザクション',
            },
            {
              type: 'doc',
              id: 'multi-storage-transactions',
              label: 'マルチストレージトランザクション',
            },
            {
              type: 'doc',
              id: 'schema-loader',
              label: 'Schema Loader',
            },
            {
              type: 'doc',
              id: 'scalardb-cluster/compatibility',
              label: 'ScalarDB Cluster 互換性マトリックス',
            },
            {
              type: 'doc',
              id: 'scalardb-cluster/developer-guide-for-scalardb-cluster-with-java-api',
              label: 'ScalarDB Cluster Java API',
            },
            {
              type: 'doc',
              id: 'scalardb-cluster/scalardb-cluster-configurations',
              label: 'ScalarDB Cluster の設定',
            },
            {
              type: 'doc',
              id: 'scalardb-cluster/scalardb-cluster-grpc-api-guide',
              label: 'ScalarDB Cluster gRPC API ガイド',
            },
            {
              type: 'doc',
              id: 'scalardb-cluster/encrypt-data-at-rest',
              label: '保存データを暗号化する',
            },
            {
              type: 'doc',
              id: 'scalardb-cluster/encrypt-wire-communications',
              label: 'ワイヤ通信を暗号化する',
            },
            {
              type: 'category',
              label: 'SQL インターフェース',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'scalardb-sql/jdbc-guide',
                  label: 'JDBC ガイド',
                },
                {
                  type: 'doc',
                  id: 'scalardb-sql/sql-api-guide',
                  label: 'API ガイド',
                },			
                {
                  type: 'doc',
                  id: 'scalardb-cluster/scalardb-cluster-sql-grpc-api-guide',
                  label: 'gRPC API ガイド',
                },
                {
                  type: 'doc',
                  id: 'scalardb-sql/spring-data-guide',
                  label: 'Spring Data ガイド',
                },
                {
                  type: 'doc',
                  id: 'scalardb-sql/grammar',
                  label: '文法',
                },
              ],
            },
            {
              type: 'category',
              label: 'GraphQL インターフェース',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'scalardb-graphql/how-to-run-two-phase-commit-transaction',
                  label: '2 フェーズコミットトランザクション',
                },
              ],
            },
            {
              type: 'category',
              label: '分析',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'scalardb-analytics-postgresql/scalardb-fdw',
                  label: 'PostgreSQL 用 ScalarDB FDW',
                },
                {
                  type: 'doc',
                  id: 'scalardb-analytics-postgresql/schema-importer',
                  label: 'PostgreSQL 用 Schema Importer',
                },
                {
                  type: 'doc',
                  id: 'scalardb-analytics-spark/version-compatibility',
                  label: 'Spark のバージョン互換性',
                },
              ],
            },
            {
              type: 'category',
              label: '.NET',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'scalardb-cluster-dotnet-client-sdk/index',
                  label: '概要',
                },
                {
                  type: 'doc',
                  id: 'scalardb-cluster-dotnet-client-sdk/getting-started-with-distributed-transactions',
                  label: '分散トランザクション',
                },
                {
                  type: 'doc',
                  id: 'scalardb-cluster-dotnet-client-sdk/getting-started-with-distributed-sql-transactions',
                  label: '分散 SQL トランザクション',
                },
                {
                  type: 'doc',
                  id: 'scalardb-cluster-dotnet-client-sdk/getting-started-with-admin-api',
                  label: 'Administrative API',
                },
                {
                  type: 'doc',
                  id: 'scalardb-cluster-dotnet-client-sdk/getting-started-with-scalardb-tables-as-csharp-classes',
                  label: 'C# クラスとしてのテーブル',
                },
                {
                  type: 'doc',
                  id: 'scalardb-cluster-dotnet-client-sdk/getting-started-with-aspnet-and-di',
                  label: 'ASP.NET Core と依存性注入',
                },
                {
                  type: 'doc',
                  id: 'scalardb-cluster-dotnet-client-sdk/getting-started-with-linq',
                  label: 'LINQ',
                },
                {
                  type: 'doc',
                  id: 'scalardb-cluster-dotnet-client-sdk/getting-started-with-two-phase-commit-transactions',
                  label: '2 フェーズコミットトランザクション',
                },
                {
                  type: 'doc',
                  id: 'scalardb-cluster-dotnet-client-sdk/getting-started-with-auth',
                  label: 'ユーザーを認証および認可する',
                },
                {
                  type: 'doc',
                  id: 'scalardb-cluster-dotnet-client-sdk/exception-handling',
                  label: '例外処理',
                },
                {
                  type: 'doc',
                  id: 'scalardb-cluster-dotnet-client-sdk/common-reference',
                  label: '共通参照',
                },
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'デプロイ',
      collapsible: true,
      items: [
        {
          type: 'doc',
          id: 'deploy-overview',
          label: '概要',
        },
        {
          type: 'doc',
          id: 'scalardb-cluster/setup-scalardb-cluster-on-kubernetes-by-using-helm-chart',
          label: 'ScalarDB Cluster をローカルにデプロイする',
        },
        {
          type: 'doc',
          id: 'scalar-kubernetes/ManualDeploymentGuideScalarDBClusterOnEKS',
          label: 'Amazon EKS に ScalarDB Cluster をデプロイする',
        },
        {
          type: 'category',
          label: '詳細',
          collapsible: true,
          items: [
            {
              type: 'doc',
              id: 'scalardb-cluster/standalone-mode',
              label: 'ScalarDB Cluster スタンドアロンモード',
            },
            {
              type: 'doc',
              id: 'scalar-kubernetes/ProductionChecklistForScalarDBCluster',
              label: 'ScalarDB Cluster の制作チェックリスト',
            },
            {
              type: 'category',
              label: 'Getting Started Guides',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'helm-charts/getting-started-scalar-helm-charts',
                  label: 'Scalar Helm Charts',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/getting-started-scalardb-cluster-tls',
                  label: 'Helm Chart を使用した TLS 対応 ScalarDB Cluster',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/getting-started-scalardb-cluster-tls-cert-manager',
                  label: 'cert-manager と Helm Chart を使用した TLS 対応 ScalarDB Cluster',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/getting-started-scalardb-analytics-postgresql',
                  label: 'Helm Chart を使用した ScalarDB Analytics with PostgreSQL',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/getting-started-monitoring',
                  label: 'Helm Chart を使用した監視用 Prometheus Operator',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/getting-started-logging',
                  label: 'Helm Chart を使用したログ記録用 Loki スタック',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/getting-started-scalar-manager',
                  label: 'Helm Chart を使用した Scalar Manager',
                },
              ],
            },
            {
              type: 'category',
              label: 'データベースセットアップガイド',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/SetupDatabaseForAWS',
                  label: 'AWS',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/SetupDatabaseForAzure',
                  label: 'Azure',
                },
              ],
            },
            {
              type: 'category',
              label: 'インストールガイド',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/HowToGetContainerImages',
                  label: 'コンテナイメージを取得する',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/AwsMarketplaceGuide',
                  label: 'AWS Marketplace からインストール',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/HowToUseContainerImages',
                  label: 'コンテナイメージを使用',
                },
              ],
            },
            {
              type: 'category',
              label: 'デプロイメントガイド',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/CreateEKSClusterForScalarDBCluster',
                  label: 'ScalarDB Cluster 用の EKS クラスターを作成する',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/CreateBastionServer',
                  label: '踏み台サーバーを作成する',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/how-to-deploy-scalardb-cluster',
                  label: 'Helm Chart を使用して ScalarDB Cluster をデプロイする',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/how-to-deploy-scalardb-analytics-postgresql',
                  label: 'Helm Chart を使用して ScalarDB Analytics with PostgreSQL をデプロイする',
                },
              ],
            },
            {
              type: 'category',
              label: '設定のガイド',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/AccessScalarProducts',
                  label: 'アプリケーションから Kubernetes 環境にアクセスする',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/HowToCreateKeyAndCertificateFiles',
                  label: '秘密鍵と証明書ファイルを作成する',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/configure-custom-values-scalardb-cluster',
                  label: 'ScalarDB Cluster のカスタム値ファイルを構成する',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/configure-custom-values-scalardb-analytics-postgresql',
                  label: 'ScalarDB Analytics with PostgreSQL のカスタム値ファイルを構成する',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/configure-custom-values-scalar-admin-for-kubernetes',
                  label: 'Scalar Admin for Kubernetes のカスタム値ファイルを構成する',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/configure-custom-values-scalar-manager',
                  label: 'Scalar Manager のカスタム値ファイルを構成する',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/configure-custom-values-envoy',
                  label: 'Scalar Envoy のカスタム値ファイルを構成する',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/mount-files-or-volumes-on-scalar-pods',
                  label: 'ScalarDB ポッドにファイルまたはボリュームをマウントする',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/use-secret-for-credentials',
                  label: 'シークレットリソースを使用する',
                },
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '移行',
      collapsible: true,
      items: [
        {
          type: 'doc',
          id: 'schema-loader-import',
          label: '既存のテーブルをインポートする',
        },
        {
          'type': 'doc',
          'id': 'scalardb-sql/migration-guide',
          'label': 'アプリケーションとデータベースの移行',
        }
      ],
    },
    {
      type: 'category',
      label: '管理',
      collapsible: true,
      items: [
        {
          type: 'doc',
          id: 'scalar-kubernetes/HowToScaleScalarDB',
          label: 'スケーリングする',
        },
        {
          type: 'doc',
          id: 'scalar-kubernetes/HowToUpgradeScalarDB',
          label: 'アップグレードする',
        },
        {
          type: 'category',
          label: 'Monitor',
          collapsible: true,
          items: [
            {
              type: 'doc',
              id: 'monitor-by-using-scalar-manager',
              label: 'Scalar Manager を使用する',
            },
            {
              type: 'category',
              label: '管理',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/K8sMonitorGuide',
                  label: 'Kubernetes モニタリングガイド',
                },
                {
                  type: 'doc',
                  id: 'scalar-manager/overview',
                  label: 'Scalar Manager の概要',
                },
                {
                  type: 'doc',
                  id: 'helm-charts/how-to-deploy-scalar-admin-for-kubernetes',
                  label: 'Kubernetes 用の Scalar Admin をデプロイする',
                },
              ]
            },
          ],
        },
        {
          type: 'category',
          label: 'バックアップと復元',
          collapsible: true,
          items: [
            {
              type: 'doc',
              id: 'manage-backup-and-restore',
              label: 'データベースをバックアップおよび復元する',
            },
            {
              type: 'category',
              label: '管理',
              collapsible: true,
              items: [
                {
                  type: 'doc',
                  id: 'backup-restore',
                  label: 'ScalarDB を通じて使用されるデータベースのバックアップと復元を行う',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/BackupNoSQL',
                  label: 'Kubernetes で NoSQL データベースをバックアップする',
                },
                {
                  type: 'doc',
                  id: 'scalar-kubernetes/RestoreDatabase',
                  label: 'Kubernetes でデータベースを復元する',
                },
              ]
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'トラブルシュート',
      collapsible: true,
      items: [
        {
          type: 'category',
          label: 'エラーコード',
          collapsible: true,
          items: [
            {
              type: 'doc',
              id: 'scalardb-core-status-codes',
              label: 'ScalarDB Core',
            },
            {
              type: 'doc',
              id: 'scalardb-cluster/scalardb-cluster-status-codes',
              label: 'ScalarDB Cluster',
            },
            {
              type: 'doc',
              id: 'scalardb-graphql/scalardb-graphql-status-codes',
              label: 'ScalarDB GraphQL',
            },
            {
              type: 'doc',
              id: 'scalardb-sql/scalardb-sql-status-codes',
              label: 'ScalarDB SQL',
            },
            {
              type: 'doc',
              id: 'scalardb-cluster/scalardb-auth-status-codes',
              label: '認証と認可',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '管理',
      collapsible: true,
      items: [
        {
          type: 'doc',
          id: 'scalar-licensing/README',
          label: '製品ライセンスキーの設定',
        },
      ],
    },
  ],
};

export default sidebars;
